# does the random module really generate rendom numbers? let's figure it out!

from random import randint
my_nums = {}

for i in range (1, 11):         # makes a dictionary with keys 1 to 10 and values = 0
    my_nums[i] = 0              # it looks like: {1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0}
print(my_nums)


n = 10_000

for i in range (n):                                # generates a random number between 1 to 10 for n times! (10,000)
    random_number = randint(1, 10)
    for j in my_nums:
        if random_number == j:
            my_nums.update({j : my_nums[j] + 1})   # adds 1 to the value whenever each key is generated by the random function
print(my_nums)


total = 0                           # validates the counting process (sum of the values should be equal to n)
for sum in my_nums.values():
    total = total + sum 
if total == n:
    print("the counting is valid\n", "n = ", n, ", total = ", total) 